version: '3.8'

services:
  graphql_server:
    build:
      context: ./servidor/Graphql
      dockerfile: Dockerfile.graphql
    ports:
      - "4000:4000"
    volumes:
      - ./servidor/Graphql:/app
    environment:
      - FLASK_ENV=development

  rest_server:
    build:
      context: ./servidor/Rest
      dockerfile: Dockerfile.rest
    ports:
      - "5000:5000"
    volumes:
      - ./servidor/Rest:/app
    environment:
      - FLASK_ENV=development

  grpc_server:
    build:
      context: ./servidor/cliente_grpc
    ports:
      - "50051:50051"
    networks:
      - cliente

  grpc_client:
    build:
      context: ./servidor/cliente_grpc
    depends_on:
      - grpc_server
    networks:
      - cliente

  cliente:
    build:
      context: ./cliente
      dockerfile: Dockerfile.cliente
    volumes:
      - ./cliente:/app

networks:
  cliente:
    driver: bridge
