# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import servico_pb2 as servico__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in servico_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServicoUsuarioStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CriarUsuario = channel.unary_unary(
                '/usuario.ServicoUsuario/CriarUsuario',
                request_serializer=servico__pb2.CriarUsuarioRequest.SerializeToString,
                response_deserializer=servico__pb2.CriarUsuarioResponse.FromString,
                _registered_method=True)
        self.ObterUsuario = channel.unary_unary(
                '/usuario.ServicoUsuario/ObterUsuario',
                request_serializer=servico__pb2.ObterUsuarioRequest.SerializeToString,
                response_deserializer=servico__pb2.ObterUsuarioResponse.FromString,
                _registered_method=True)
        self.AtualizarUsuario = channel.unary_unary(
                '/usuario.ServicoUsuario/AtualizarUsuario',
                request_serializer=servico__pb2.AtualizarUsuarioRequest.SerializeToString,
                response_deserializer=servico__pb2.AtualizarUsuarioResponse.FromString,
                _registered_method=True)
        self.ApagarUsuario = channel.unary_unary(
                '/usuario.ServicoUsuario/ApagarUsuario',
                request_serializer=servico__pb2.ApagarUsuarioRequest.SerializeToString,
                response_deserializer=servico__pb2.ApagarUsuarioResponse.FromString,
                _registered_method=True)
        self.ExportarUsuarios = channel.unary_unary(
                '/usuario.ServicoUsuario/ExportarUsuarios',
                request_serializer=servico__pb2.ExportarUsuariosRequest.SerializeToString,
                response_deserializer=servico__pb2.ExportarUsuariosResponse.FromString,
                _registered_method=True)
        self.ImportarUsuarios = channel.unary_unary(
                '/usuario.ServicoUsuario/ImportarUsuarios',
                request_serializer=servico__pb2.ImportarUsuariosRequest.SerializeToString,
                response_deserializer=servico__pb2.ImportarUsuariosResponse.FromString,
                _registered_method=True)


class ServicoUsuarioServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CriarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObterUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AtualizarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApagarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportarUsuarios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportarUsuarios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicoUsuarioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CriarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarUsuario,
                    request_deserializer=servico__pb2.CriarUsuarioRequest.FromString,
                    response_serializer=servico__pb2.CriarUsuarioResponse.SerializeToString,
            ),
            'ObterUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterUsuario,
                    request_deserializer=servico__pb2.ObterUsuarioRequest.FromString,
                    response_serializer=servico__pb2.ObterUsuarioResponse.SerializeToString,
            ),
            'AtualizarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.AtualizarUsuario,
                    request_deserializer=servico__pb2.AtualizarUsuarioRequest.FromString,
                    response_serializer=servico__pb2.AtualizarUsuarioResponse.SerializeToString,
            ),
            'ApagarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.ApagarUsuario,
                    request_deserializer=servico__pb2.ApagarUsuarioRequest.FromString,
                    response_serializer=servico__pb2.ApagarUsuarioResponse.SerializeToString,
            ),
            'ExportarUsuarios': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportarUsuarios,
                    request_deserializer=servico__pb2.ExportarUsuariosRequest.FromString,
                    response_serializer=servico__pb2.ExportarUsuariosResponse.SerializeToString,
            ),
            'ImportarUsuarios': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportarUsuarios,
                    request_deserializer=servico__pb2.ImportarUsuariosRequest.FromString,
                    response_serializer=servico__pb2.ImportarUsuariosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'usuario.ServicoUsuario', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('usuario.ServicoUsuario', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServicoUsuario(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CriarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuario.ServicoUsuario/CriarUsuario',
            servico__pb2.CriarUsuarioRequest.SerializeToString,
            servico__pb2.CriarUsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObterUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuario.ServicoUsuario/ObterUsuario',
            servico__pb2.ObterUsuarioRequest.SerializeToString,
            servico__pb2.ObterUsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AtualizarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuario.ServicoUsuario/AtualizarUsuario',
            servico__pb2.AtualizarUsuarioRequest.SerializeToString,
            servico__pb2.AtualizarUsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApagarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuario.ServicoUsuario/ApagarUsuario',
            servico__pb2.ApagarUsuarioRequest.SerializeToString,
            servico__pb2.ApagarUsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportarUsuarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuario.ServicoUsuario/ExportarUsuarios',
            servico__pb2.ExportarUsuariosRequest.SerializeToString,
            servico__pb2.ExportarUsuariosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportarUsuarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuario.ServicoUsuario/ImportarUsuarios',
            servico__pb2.ImportarUsuariosRequest.SerializeToString,
            servico__pb2.ImportarUsuariosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
