FROM python:latest

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY grpc_server.py .
COPY servico.proto ./grpc/
COPY servico_pb2.py .
COPY servico_pb2_grpc.py .

EXPOSE 50051

CMD ["python", "grpc_server.py"]
