# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: servico.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'servico.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservico.proto\x12\x07usuario\"2\n\x07Usuario\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"2\n\x13\x43riarUsuarioRequest\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"4\n\x14\x43riarUsuarioResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08mensagem\x18\x02 \x01(\t\"!\n\x13ObterUsuarioRequest\x12\n\n\x02id\x18\x01 \x01(\t\"9\n\x14ObterUsuarioResponse\x12!\n\x07usuario\x18\x01 \x01(\x0b\x32\x10.usuario.Usuario\"_\n\x17\x41tualizarUsuarioRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\x04nome\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05\x65mail\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_nomeB\x08\n\x06_email\",\n\x18\x41tualizarUsuarioResponse\x12\x10\n\x08mensagem\x18\x01 \x01(\t\"\"\n\x14\x41pagarUsuarioRequest\x12\n\n\x02id\x18\x01 \x01(\t\")\n\x15\x41pagarUsuarioResponse\x12\x10\n\x08mensagem\x18\x01 \x01(\t\"*\n\x17\x45xportarUsuariosRequest\x12\x0f\n\x07\x66ormato\x18\x01 \x01(\t\")\n\x18\x45xportarUsuariosResponse\x12\r\n\x05\x64\x61\x64os\x18\x01 \x01(\t\"(\n\x17ImportarUsuariosRequest\x12\r\n\x05\x64\x61\x64os\x18\x01 \x01(\t\")\n\x18ImportarUsuariosResponse\x12\r\n\x05\x64\x61\x64os\x18\x01 \x01(\t2\x85\x04\n\x0eServicoUsuario\x12K\n\x0c\x43riarUsuario\x12\x1c.usuario.CriarUsuarioRequest\x1a\x1d.usuario.CriarUsuarioResponse\x12K\n\x0cObterUsuario\x12\x1c.usuario.ObterUsuarioRequest\x1a\x1d.usuario.ObterUsuarioResponse\x12W\n\x10\x41tualizarUsuario\x12 .usuario.AtualizarUsuarioRequest\x1a!.usuario.AtualizarUsuarioResponse\x12N\n\rApagarUsuario\x12\x1d.usuario.ApagarUsuarioRequest\x1a\x1e.usuario.ApagarUsuarioResponse\x12W\n\x10\x45xportarUsuarios\x12 .usuario.ExportarUsuariosRequest\x1a!.usuario.ExportarUsuariosResponse\x12W\n\x10ImportarUsuarios\x12 .usuario.ImportarUsuariosRequest\x1a!.usuario.ImportarUsuariosResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'servico_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USUARIO']._serialized_start=26
  _globals['_USUARIO']._serialized_end=76
  _globals['_CRIARUSUARIOREQUEST']._serialized_start=78
  _globals['_CRIARUSUARIOREQUEST']._serialized_end=128
  _globals['_CRIARUSUARIORESPONSE']._serialized_start=130
  _globals['_CRIARUSUARIORESPONSE']._serialized_end=182
  _globals['_OBTERUSUARIOREQUEST']._serialized_start=184
  _globals['_OBTERUSUARIOREQUEST']._serialized_end=217
  _globals['_OBTERUSUARIORESPONSE']._serialized_start=219
  _globals['_OBTERUSUARIORESPONSE']._serialized_end=276
  _globals['_ATUALIZARUSUARIOREQUEST']._serialized_start=278
  _globals['_ATUALIZARUSUARIOREQUEST']._serialized_end=373
  _globals['_ATUALIZARUSUARIORESPONSE']._serialized_start=375
  _globals['_ATUALIZARUSUARIORESPONSE']._serialized_end=419
  _globals['_APAGARUSUARIOREQUEST']._serialized_start=421
  _globals['_APAGARUSUARIOREQUEST']._serialized_end=455
  _globals['_APAGARUSUARIORESPONSE']._serialized_start=457
  _globals['_APAGARUSUARIORESPONSE']._serialized_end=498
  _globals['_EXPORTARUSUARIOSREQUEST']._serialized_start=500
  _globals['_EXPORTARUSUARIOSREQUEST']._serialized_end=542
  _globals['_EXPORTARUSUARIOSRESPONSE']._serialized_start=544
  _globals['_EXPORTARUSUARIOSRESPONSE']._serialized_end=585
  _globals['_IMPORTARUSUARIOSREQUEST']._serialized_start=587
  _globals['_IMPORTARUSUARIOSREQUEST']._serialized_end=627
  _globals['_IMPORTARUSUARIOSRESPONSE']._serialized_start=629
  _globals['_IMPORTARUSUARIOSRESPONSE']._serialized_end=670
  _globals['_SERVICOUSUARIO']._serialized_start=673
  _globals['_SERVICOUSUARIO']._serialized_end=1190
# @@protoc_insertion_point(module_scope)
