FROM python:latest

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY graphql_server.py .
#COPY ../graphql/ ./graphql/

EXPOSE 4000

CMD ["python", "graphql_server.py"]
