# Usar imagem oficial do Python
FROM python:3.12-slim

# Diretório de trabalho
WORKDIR /app

# Copiar requirements e instalar
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o código
COPY . .

# Expor porta
EXPOSE 5000

# Comando para arrancar
CMD ["python", "graphql_server.py"]
